package nz.co.concreteOnlineA.admin;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Container;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import nz.co.concreteOnlineA.Utilities.ConsoleWindow;
import nz.co.concreteOnlineA.login.login;
import nz.co.concreteOnlineA.services.FileReceiver;
import nz.co.concreteOnlineA.services.ReadFromFile;

/**
 *
 * @author Tyler Costa
 */
public class AdminDisplayNEW extends javax.swing.JFrame implements Runnable {

    Thread t = new Thread(this);

    public String user;

    int hour, second, minute;
    Calendar calendar;
    SimpleDateFormat timeFormat;
    Container container;
    CardLayout cardlayout;
    String time;
    ConsoleWindow consoleWindow = new ConsoleWindow();

    /**
     * Creates new form AdminDisplay
     */
    public AdminDisplayNEW() {
        initComponents();
        initClock();

        initPages();
        beginConsole();

        this.setTitle("Concrete Online Admin | " + user);
        ReadFromFile RFF = new ReadFromFile("testdoc");

    }

    void initPages() {
        mainPanel.add(new JobStack());

    }

    void initClock() {
        t.start();

    }

    public void beginConsole() {
        printConsoleMessage("Program begun", false);
        //printConsoleMessage("Logged in as:  " + user , true);
    }

    public void printConsoleMessage(String message, boolean getTime) {
        System.out.println("");
        if (getTime == true) {
            consoleWindow.ConsoleDLM.addElement(user + " :: " + message + " :: at " + time);

        } else {
            consoleWindow.ConsoleDLM.addElement(user + " :: " + message + " ");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_jobStack = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_activeJobs = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_prevJob = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btn_options = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_adminControls = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        adminDashLabel = new javax.swing.JLabel();
        loggedInAccountLabel = new javax.swing.JLabel();
        datePanel = new javax.swing.JPanel();
        dateStringLabel = new javax.swing.JLabel();
        clockPanel = new javax.swing.JPanel();
        clockLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        OpenConsoleButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        connectionLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 750));

        menuPanel.setBackground(new java.awt.Color(77, 77, 77));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/co/concreteOnlineA/assets/logo.png"))); // NOI18N
        menuPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 16, -1, -1));
        menuPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 135, 260, 16));

        btn_jobStack.setBackground(new java.awt.Color(153, 153, 153));
        btn_jobStack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_jobStackMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Available Jobs");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/co/concreteOnlineA/assets/icons8-home-50 (1).png"))); // NOI18N

        javax.swing.GroupLayout btn_jobStackLayout = new javax.swing.GroupLayout(btn_jobStack);
        btn_jobStack.setLayout(btn_jobStackLayout);
        btn_jobStackLayout.setHorizontalGroup(
            btn_jobStackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_jobStackLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_jobStackLayout.setVerticalGroup(
            btn_jobStackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_jobStackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuPanel.add(btn_jobStack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, 50));

        btn_activeJobs.setBackground(new java.awt.Color(102, 102, 102));
        btn_activeJobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_activeJobsMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Accepted Jobs");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/co/concreteOnlineA/assets/icons8-stack-50 (1).png"))); // NOI18N

        javax.swing.GroupLayout btn_activeJobsLayout = new javax.swing.GroupLayout(btn_activeJobs);
        btn_activeJobs.setLayout(btn_activeJobsLayout);
        btn_activeJobsLayout.setHorizontalGroup(
            btn_activeJobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_activeJobsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_activeJobsLayout.setVerticalGroup(
            btn_activeJobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        menuPanel.add(btn_activeJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 50));

        btn_prevJob.setBackground(new java.awt.Color(102, 102, 102));
        btn_prevJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_prevJobMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Completed Jobs");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/co/concreteOnlineA/assets/icons8-stack-50 (1).png"))); // NOI18N

        javax.swing.GroupLayout btn_prevJobLayout = new javax.swing.GroupLayout(btn_prevJob);
        btn_prevJob.setLayout(btn_prevJobLayout);
        btn_prevJobLayout.setHorizontalGroup(
            btn_prevJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_prevJobLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btn_prevJobLayout.setVerticalGroup(
            btn_prevJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        menuPanel.add(btn_prevJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, -1));

        btn_options.setBackground(new java.awt.Color(102, 102, 102));
        btn_options.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_optionsMousePressed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/co/concreteOnlineA/assets/icons8-settings-50 (1).png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Options");

        javax.swing.GroupLayout btn_optionsLayout = new javax.swing.GroupLayout(btn_options);
        btn_options.setLayout(btn_optionsLayout);
        btn_optionsLayout.setHorizontalGroup(
            btn_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_optionsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        btn_optionsLayout.setVerticalGroup(
            btn_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuPanel.add(btn_options, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 270, 50));

        btn_adminControls.setBackground(new java.awt.Color(102, 102, 102));
        btn_adminControls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_adminControlsMousePressed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/co/concreteOnlineA/assets/icons8-admin-settings-male-50 (1).png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Admin Controls");

        javax.swing.GroupLayout btn_adminControlsLayout = new javax.swing.GroupLayout(btn_adminControls);
        btn_adminControls.setLayout(btn_adminControlsLayout);
        btn_adminControlsLayout.setHorizontalGroup(
            btn_adminControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_adminControlsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
        );
        btn_adminControlsLayout.setVerticalGroup(
            btn_adminControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        menuPanel.add(btn_adminControls, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 270, -1));

        jButton1.setBackground(new java.awt.Color(234, 110, 38));
        jButton1.setText("Logout");
        jButton1.setBorderPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menuPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 100, 50));

        headerPanel.setBackground(new java.awt.Color(77, 77, 77));

        adminDashLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        adminDashLabel.setText("Admin Dashboard");

        loggedInAccountLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        loggedInAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        loggedInAccountLabel.setText("Logged in as: "+ user
        );

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(adminDashLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addGap(332, 332, 332)
                .addComponent(loggedInAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminDashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loggedInAccountLabel))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        datePanel.setBackground(new java.awt.Color(234, 110, 38));

        dateStringLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        dateStringLabel.setForeground(new java.awt.Color(77, 77, 77));
        dateStringLabel.setText("date");

        clockPanel.setBackground(new java.awt.Color(234, 110, 38));

        clockLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clockLabel.setForeground(new java.awt.Color(77, 77, 77));
        clockLabel.setText("time");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Time: ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Date:");

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(77, 77, 77));
        dateLabel.setText("date");

        javax.swing.GroupLayout clockPanelLayout = new javax.swing.GroupLayout(clockPanel);
        clockPanel.setLayout(clockPanelLayout);
        clockPanelLayout.setHorizontalGroup(
            clockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clockPanelLayout.createSequentialGroup()
                .addGroup(clockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, clockPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, clockPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        clockPanelLayout.setVerticalGroup(
            clockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clockPanelLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(clockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(clockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        OpenConsoleButton.setText("Open Console");
        OpenConsoleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenConsoleButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Test");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Grab File");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        connectionLabel.setText("Connecting...");

        javax.swing.GroupLayout datePanelLayout = new javax.swing.GroupLayout(datePanel);
        datePanel.setLayout(datePanelLayout);
        datePanelLayout.setHorizontalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OpenConsoleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(connectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(datePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(dateStringLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addGap(362, 362, 362)))
        );
        datePanelLayout.setVerticalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clockPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenConsoleButton)
                    .addComponent(jButton2)
                    .addComponent(connectionLabel))
                .addContainerGap())
            .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(datePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dateStringLabel)
                    .addGap(0, 92, Short.MAX_VALUE)))
        );

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_jobStackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jobStackMousePressed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(new JobStack());
        mainPanel.repaint();
        mainPanel.revalidate();

        setColor(btn_jobStack);
        resetColor(btn_activeJobs);
        resetColor(btn_options);
        resetColor(btn_prevJob);
        resetColor(btn_adminControls);
        printConsoleMessage("Job Stack Opened", true);

        //cardlayout.show(container, "a");
        // mainContentPane.setSelectedIndex(0);

    }//GEN-LAST:event_btn_jobStackMousePressed

    private void btn_activeJobsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_activeJobsMousePressed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(new AcceptedJobs());
        mainPanel.repaint();
        mainPanel.revalidate();

        setColor(btn_activeJobs);
        resetColor(btn_jobStack);
        resetColor(btn_options);
        resetColor(btn_adminControls);
        resetColor(btn_prevJob);
        // mainContentPane.setSelectedIndex(1);
//cardlayout.show(container, "b");
        // mainPanel.add(new AcceptedJobs());
        printConsoleMessage("Accepted Jobs Opened", true);

    }//GEN-LAST:event_btn_activeJobsMousePressed

    private void btn_prevJobMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prevJobMousePressed
        // TODO add your handling code here:
        setColor(btn_prevJob);
        resetColor(btn_jobStack);
        resetColor(btn_adminControls);
        resetColor(btn_options);
        resetColor(btn_activeJobs);

        printConsoleMessage("Job History Opened", true);

        // mainContentPane.setSelectedIndex(2);
    }//GEN-LAST:event_btn_prevJobMousePressed

    private void btn_optionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_optionsMousePressed
        // TODO add your handling code here:
        setColor(btn_options);
        resetColor(btn_jobStack);
        resetColor(btn_activeJobs);
        resetColor(btn_adminControls);
        resetColor(btn_prevJob);

        printConsoleMessage("Options Opened", true);

        //  mainContentPane.setSelectedIndex(3);

    }//GEN-LAST:event_btn_optionsMousePressed

    private void btn_adminControlsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminControlsMousePressed
        //    TODO add your handling code here:

        mainPanel.removeAll();
        mainPanel.add(new AdminControls());
        mainPanel.repaint();
        mainPanel.revalidate();

        setColor(btn_adminControls);
        resetColor(btn_jobStack);
        resetColor(btn_activeJobs);
        resetColor(btn_options);
        resetColor(btn_prevJob);

        printConsoleMessage("Admin Controls Opened", true);

        // mainContentPane.setSelectedIndex(4);
    }//GEN-LAST:event_btn_adminControlsMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        printConsoleMessage("Logging out", true);

        this.dispose();
        new login().setVisible(true);
        t.interrupt();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void OpenConsoleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenConsoleButtonActionPerformed
        // TODO add your handling code here:

        consoleWindow.setVisible(true);
        consoleWindow.setTitle("Console");
        consoleWindow.setDefaultCloseOperation(ConsoleWindow.DISPOSE_ON_CLOSE);
        consoleWindow.setResizable(false);
    }//GEN-LAST:event_OpenConsoleButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        printConsoleMessage("Button Pressed", true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayNEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayNEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayNEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayNEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDisplayNEW().setVisible(true);
            }
        });
    }

    void setColor(JPanel panel) {
        panel.setBackground(new Color(153, 153, 153));

    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(102, 102, 102));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OpenConsoleButton;
    private javax.swing.JLabel adminDashLabel;
    private javax.swing.JPanel btn_activeJobs;
    private javax.swing.JPanel btn_adminControls;
    private javax.swing.JPanel btn_jobStack;
    private javax.swing.JPanel btn_options;
    private javax.swing.JPanel btn_prevJob;
    private javax.swing.JLabel clockLabel;
    private javax.swing.JPanel clockPanel;
    private javax.swing.JLabel connectionLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel datePanel;
    private javax.swing.JLabel dateStringLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel loggedInAccountLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
@Override
    public void run() {
        while (true) {
            try {
                receiveFile();
            } catch (IOException ex) {
                Logger.getLogger(AdminDisplayNEW.class.getName()).log(Level.SEVERE, null, ex);
            }

            Calendar cal = Calendar.getInstance();
            hour = cal.get(Calendar.HOUR_OF_DAY);
            minute = cal.get(Calendar.MINUTE);
            second = cal.get(Calendar.SECOND);
            Date dat = cal.getTime();
            Date date = new Date();
            LocalDate localDate = LocalDate.now();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat sdf12 = new SimpleDateFormat("hh:mm:ss aa");
            SimpleDateFormat dow = new SimpleDateFormat("EEEE, MMM d, yyyy");

            String time12 = sdf12.format(dat);
            String datee = sdf.format(date);
            String fullDate = dow.format(date);
            System.out.println(fullDate + " " + time12);
            clockLabel.setText(time12);
            dateLabel.setText(datee);
            dateStringLabel.setText(fullDate);
            time = time12;
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                System.out.println("Thread killed");//Logger.getLogger(MainDisplay.class.getName()).log(Level.SEVERE, null, ex);
                break;
            }
        }

    }
    boolean connEst;
    int connectCount = 0;

    private void receiveFile() throws IOException {
        FileReceiver FR = new FileReceiver();
        connEst = FR.connectionEstablished;

        if (connEst == false) {
            connectCount++;
            connectionLabel.setForeground(Color.red);
            connectionLabel.setBackground(Color.black);
            connectionLabel.setText("Could Not Connect to Server, tried " + connectCount + " times.");
        } else {
            connectionLabel.setForeground(Color.green);
            connectionLabel.setText("Connection to server established. ");
            connectCount = 0;
        }

    }

}
